# Generated by Django 5.2 on 2025-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Unnamed User', max_length=100),
            preserve_default=False,
        ),
    ]
