# Generated by Django 5.2 on 2025-05-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_uid_alter_project_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergrad', 'Undergrad'), ('Graduate', 'Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
