# Generated by Django 5.2 on 2025-05-03 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, related_name='saved_by_set', to='core.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_projects_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
