# Generated by Django 5.2 on 2025-05-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_saved_projects_alter_project_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='saved_projects',
        ),
    ]
