# Generated by Django 5.2 on 2025-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_saved_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_projects',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='core.project'),
        ),
    ]
